### PR TITLE
Minitest support

### PR DESCRIPTION
**Pull request by jeremy**
``` ruby
require 'capybara-inline-screenshot/minitest'

class SystemTest < Minitest::Test
  include CapybaraInlineScreenshot::Minitest
end
```

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks so much! :)

**Comment by toolmantim** [comment]
I've updated the [Readme.md](https://github.com/buildkite/capybara-inline-screenshot/blob/master/README.md) — do those instructions look good to you?

**Comment by jeremy** [comment]
👍

**Comment by toolmantim** [comment]
Thanks, v2.1.0 has been pushed

**Comment by jeremy** [comment]
Thanks @toolmantim 😁

**Comment by toolmantim** [comment]
Thank you, I just did the easy stuff :dancers:

**Pull request merged**
